FROM bcit/centos:<%= image.labels['centos_version'] %>
ENV TZ America/Vancouver
ENV HOME /application

<%= snippet('labels', binding) -%>

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
        epel-release \
        http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
 && yum-config-manager --enable remi-php70 \
 && yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
    file \
    less \
    perl-Image-ExifTool \
    php-fpm \
    php-cli \
    php-xml \
    php-gd \
    php-odbc \
    php-intl \
    php-bcmath \
    php-ldap \
    php-soap \
    php-common \
    php-xmlrpc \
    php-dba \
    php-enchant \
    php-dbg \
    php-json \
    php-mbstring \
    php-process \
    php-pdo \
    php-recode \
    php-mysqlnd \
    php-gmp \
    php-opcache \
    php-pecl-gmagick \
    php-pecl-redis \
    php-pecl-zip \
    php-pecl-zmq \
    unoconv \
    xpdf

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
    http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm \
 && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro \
 && yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
        ffmpeg \
        gpac

RUN mkdir -p /application \
 && chown 0:0 /application \
 && chmod 775 /application

RUN sed -i "s/^error_log.*/error_log = \/proc\/self\/fd\/2/" /etc/php-fpm.conf \
 && sed -i "s/^session.cache_limiter.*/session.cache_limiter =/" /etc/php.ini \
 && sed -i "s/^session.hash_bits_per_character.*/session.hash_bits_per_character = 6/" /etc/php.ini \
 && sed -i "s/^session.hash_function.*/session.hash_function = 1/" /etc/php.ini \
 && sed -i "s/^;session.cookie_secure.*/session.cookie_secure = 1/" /etc/php.ini \
 && chown -R 0:0 \
        /etc/php-fpm.conf \
        /etc/php-fpm.d \
        /etc/php.d \
        /etc/php.ini \
 && chmod 644 \
        /etc/php-fpm.conf \
        /etc/php.ini \
 && chmod 0775 \
        /etc/php-fpm.d \
        /etc/php.d \
 && find \
        /etc/php-fpm.d \
        /etc/php.d \
        -type f -exec chmod 664 {} \;

RUN mkdir -p /run/php-fpm \
 && chown 0:0 /run/php-fpm \
 && chmod 1777 /run/php-fpm

COPY 50-copy-config.sh           /docker-entrypoint.d/
COPY 55-php.ini-date.timezone.sh /docker-entrypoint.d/

WORKDIR /application
EXPOSE 9000
CMD ["/usr/sbin/php-fpm", "-F", "-O", "-y", "/etc/php-fpm.conf"]
